[package]
name = "nommo_vol_driver"
version = "0.1.0"
authors = ["luke"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "1.2.2"
rust-pulsectl = "0.2.6"
subprocess = "0.2.4"